/*
 * login.java
 *
 * Created on __DATE__, __TIME__
 */

package View;

import java.sql.SQLException;
import javax.swing.JOptionPane;
import fuwuqi.MyClient;
import User.Student;

/**
 *
 * @author  __USER__
 */
public class login extends javax.swing.JFrame {

	/** Creates new form login */
	public login() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

buttonGroup1 = new javax.swing.ButtonGroup();
jPanel1 = new javax.swing.JPanel();
jLabel1 = new javax.swing.JLabel();
jTextField1 = new javax.swing.JTextField();
jLabel2 = new javax.swing.JLabel();
jRadioButton1 = new javax.swing.JRadioButton();
jRadioButton2 = new javax.swing.JRadioButton();
jRadioButton3 = new javax.swing.JRadioButton();
jButton1 = new javax.swing.JButton();
jPasswordField1 = new javax.swing.JPasswordField();

setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

jPanel1.setBackground(new java.awt.Color(226, 220, 220));
jPanel1.setToolTipText("\u6ce8\u518c");

jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/’À∫≈.png"))); // NOI18N
jLabel1.setText("\u8d26\u53f7:");

jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/√‹¬Î.png"))); // NOI18N
jLabel2.setText("\u5bc6\u7801\uff1a");

buttonGroup1.add(jRadioButton1);
jRadioButton1.setText("\u5b66\u751f");
jRadioButton1.setOpaque(false);

buttonGroup1.add(jRadioButton2);
jRadioButton2.setText("\u8001\u5e08");
jRadioButton2.setOpaque(false);

buttonGroup1.add(jRadioButton3);
jRadioButton3.setText("\u7ba1\u7406\u5458");
jRadioButton3.setOpaque(false);

jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/µ«¬Ω.png"))); // NOI18N
jButton1.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
try {
	jButton1ActionPerformed(evt);
} catch (ClassNotFoundException e) {
	// TODO Auto-generated catch block
	e.printStackTrace();
} catch (SQLException e) {
	// TODO Auto-generated catch block
	e.printStackTrace();
}
}
});

jPasswordField1.setText("jPasswordField1");
jPasswordField1.setEchoChar((char) 0);

javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
jPanel1.setLayout(jPanel1Layout);
jPanel1Layout.setHorizontalGroup(
jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(jPanel1Layout.createSequentialGroup()
.addContainerGap()
.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(jPanel1Layout.createSequentialGroup()
.addComponent(jLabel1)
.addContainerGap(249, Short.MAX_VALUE))
.addGroup(jPanel1Layout.createSequentialGroup()
.addComponent(jLabel2)
.addContainerGap(240, Short.MAX_VALUE))
.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
.addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
.addContainerGap())
.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
.addComponent(jRadioButton2)
.addGap(32, 32, 32)
.addComponent(jRadioButton3)
.addGap(44, 44, 44))))
.addGroup(jPanel1Layout.createSequentialGroup()
.addGap(31, 31, 31)
.addComponent(jRadioButton1)
.addContainerGap(223, Short.MAX_VALUE))
.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
.addContainerGap()
.addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, Short.MAX_VALUE)
.addGap(19, 19, 19))
.addGroup(jPanel1Layout.createSequentialGroup()
.addContainerGap()
.addComponent(jPasswordField1, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
.addGap(19, 19, 19))
);
jPanel1Layout.setVerticalGroup(
jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(jPanel1Layout.createSequentialGroup()
.addGap(31, 31, 31)
.addComponent(jLabel1)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
.addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
.addGap(31, 31, 31)
.addComponent(jLabel2)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
.addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
.addGap(28, 28, 28)
.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(jRadioButton1)
.addComponent(jRadioButton2)
.addComponent(jRadioButton3))
.addGap(29, 29, 29)
.addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
.addContainerGap(102, Short.MAX_VALUE))
);

javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
getContentPane().setLayout(layout);
layout.setHorizontalGroup(
layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
);
layout.setVerticalGroup(
layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
);

pack();
}// </editor-fold>

	//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)
			throws ClassNotFoundException, SQLException {
		// TODO add your handling code here:
		String id = jTextField1.getText();
		String pwe = new String(jPasswordField1.getPassword());
		if (id.equals("") || pwe.equals("")) {
			JOptionPane.showMessageDialog(this, "«Î ‰»Î’À∫≈√‹¬Î");
		} else if (evt.getSource().equals(jButton1)&& jRadioButton1.isSelected()) {
			try {
				MyClient c = new MyClient();
				Student u = c.login(id, pwe);
				if (u == null) {
					JOptionPane.showMessageDialog(this, "’À∫≈√‹¬Î¥ÌŒÛ");
				} else {
					JOptionPane.showMessageDialog(this, "µ«¬Ω≥…π¶");
					new Studenthome(u.getNams()).setVisible(true);
					dispose();
				}
			} catch (Exception e) {
				// TODO Auto-generated catch block
				JOptionPane.showMessageDialog(this, e.getMessage());
			}
		} else if (evt.getSource().equals(jButton1)
				&& jRadioButton2.isSelected()) {

			try {
				MyClient c = new MyClient();
				Student u = c.login1(id, pwe);
				if (u == null) {
					JOptionPane.showMessageDialog(this, "’À∫≈√‹¬Î¥ÌŒÛ");
				} else {
					JOptionPane.showMessageDialog(this, "µ«¬Ω≥…π¶");
					new Teacherhome(u.getNams()).setVisible(true);
					dispose();

				}
			} catch (Exception e) {
				// TODO Auto-generated catch block
				JOptionPane.showMessageDialog(this, e.getMessage());
			}
		} else if (evt.getSource().equals(jButton1)
				&& jRadioButton3.isSelected()) {
			try {
				MyClient c = new MyClient();
				Student u = c.login2(id, pwe);
				if (u == null) {
					JOptionPane.showMessageDialog(this, "’À∫≈√‹¬Î¥ÌŒÛ");
				} else {
					JOptionPane.showMessageDialog(this, "µ«¬Ω≥…π¶");
					new Administratorshome(u.getNams()).setVisible(true);
					dispose();

				}
			} catch (Exception e) {
				// TODO Auto-generated catch block
				JOptionPane.showMessageDialog(this, e.getMessage());
			}
		}
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {

		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new login().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.ButtonGroup buttonGroup1;
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPasswordField jPasswordField1;
	private javax.swing.JRadioButton jRadioButton1;
	private javax.swing.JRadioButton jRadioButton2;
	private javax.swing.JRadioButton jRadioButton3;
	private javax.swing.JTextField jTextField1;
	// End of variables declaration//GEN-END:variables

}