/*
 * Outoftestpaper.java
 *
 * Created on __DATE__, __TIME__
 */

package View;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

import paper.addQuestion;

import Shujuku.Shujukulianjie;

/**
 *
 * @author  __USER__
 */
public class Outoftestpaper extends javax.swing.JFrame {

	/** Creates new form Outoftestpaper */
	public Outoftestpaper(String a) {
		initComponents();
		jLabel6.setText(a);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {
		Dimension scrSize=Toolkit.getDefaultToolkit().getScreenSize();  
	    this.setLocation((scrSize.width)/2, (scrSize.height)/2);
	    this.setResizable(false);
		jPanel1 = new javax.swing.JPanel();
		jButton1 = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jFileChooser1 = new javax.swing.JFileChooser();
		jLabel3 = new javax.swing.JLabel();
		jFileChooser2 = new javax.swing.JFileChooser();
		jLabel4 = new javax.swing.JLabel();
		jFileChooser3 = new javax.swing.JFileChooser();
		jLabel5 = new javax.swing.JLabel();
		jFileChooser4 = new javax.swing.JFileChooser();
		jLabel6 = new javax.swing.JLabel();
		jButton2 = new javax.swing.JButton();
		jLabel7 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jPanel1.setBackground(new java.awt.Color(255, 255, 255));

		jButton1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14));
		jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/img/返回首页.png"))); // NOI18N
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jLabel1.setText("\u51fa\u5377");

		jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14));
		jLabel2.setText("\u672c\u8bd5\u5377\u5355\u9009\u9898");

		jFileChooser1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jFileChooser1ActionPerformed(evt);
			}
		});

		jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14));
		jLabel3.setText("\u672c\u8bd5\u5377\u591a\u9009\u9898");

		jFileChooser2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jFileChooser2ActionPerformed(evt);
			}
		});

		jLabel4.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14));
		jLabel4.setText("\u672c\u8bd5\u5377\u5224\u65ad\u9898");

		jFileChooser3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jFileChooser3ActionPerformed(evt);
			}
		});

		jLabel5.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14));
		jLabel5.setText("\u672c\u8bd5\u5377\u586b\u7a7a\u9898");

		jFileChooser4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jFileChooser4ActionPerformed(evt);
			}
		});

		jLabel6.setText("jLabel6");

		jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/img/出卷按钮.png"))); // NOI18N
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jLabel7.setText("\u8bd5\u5377\u540d\uff1a");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel2)
																		.addGap(
																				482,
																				482,
																				482)
																		.addComponent(
																				jLabel4))
														.addComponent(
																jFileChooser2,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																540,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jFileChooser1,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								552,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jLabel3))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jFileChooser3,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								552,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addGroup(
																								jPanel1Layout
																										.createSequentialGroup()
																										.addGap(
																												10,
																												10,
																												10)
																										.addGroup(
																												jPanel1Layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING)
																														.addComponent(
																																jFileChooser4,
																																javax.swing.GroupLayout.PREFERRED_SIZE,
																																552,
																																javax.swing.GroupLayout.PREFERRED_SIZE)
																														.addComponent(
																																jLabel5)))))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jButton1,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								100,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addGroup(
																								jPanel1Layout
																										.createSequentialGroup()
																										.addGap(
																												36,
																												36,
																												36)
																										.addComponent(
																												jLabel7)
																										.addGap(
																												18,
																												18,
																												18)
																										.addComponent(
																												jTextField1,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												180,
																												javax.swing.GroupLayout.PREFERRED_SIZE)))
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								jPanel1Layout
																										.createSequentialGroup()
																										.addGap(
																												32,
																												32,
																												32)
																										.addComponent(
																												jLabel1)
																										.addGap(
																												18,
																												18,
																												18)
																										.addComponent(
																												jLabel6))
																						.addGroup(
																								jPanel1Layout
																										.createSequentialGroup()
																										.addGap(
																												18,
																												18,
																												18)
																										.addComponent(
																												jButton2,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												190,
																												javax.swing.GroupLayout.PREFERRED_SIZE)))))
										.addContainerGap(29, Short.MAX_VALUE)));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jButton1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																27,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel1)
														.addComponent(jLabel6))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jTextField1,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jLabel7))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jLabel2)
																						.addComponent(
																								jLabel4,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								19,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addComponent(
																				jButton2,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				23,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(
																				35,
																				35,
																				35)))
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(
																jFileChooser1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																248,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jFileChooser3,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																248,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel3)
														.addComponent(
																jLabel5,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																19,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jFileChooser2,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																248,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jFileChooser4,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																248,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addContainerGap(40, Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		new Teacherhome(jLabel6.getText()).setVisible(true);
		this.dispose();
	}

	public List<Simple2> getText2(File f) {//填空题
		List<Simple2> simples = new ArrayList<Simple2>();
		try {
			FileReader reader = new FileReader(f);
			BufferedReader bfReader = new BufferedReader(reader);
			String text = null;
			while ((text = bfReader.readLine()) != null) {
				String[] texts = text.split(" ");
				Simple2 simple = new Simple2();
				simple.tihao = texts[0];
				simple.timu = texts[1];
				simple.answer = texts[2];
				simples.add(simple);
			}
		} catch (Exception e) {
			e.printStackTrace();
			JOptionPane.showMessageDialog(this, "txt内容有问题");
		}
		return simples;
	}

	public void insert2(Simple2 simple) throws ClassNotFoundException,
			SQLException {//填空题
		Shujukulianjie a = new Shujukulianjie();
		String b = jTextField1.getText();
		String sql = "INSERT INTO " + b
				+ "tiankong(tihao,timu,A,B,C,D,answer) VALUES(?,?,?,?,?,?,?)";
		PreparedStatement sm = null;
		try {
			sm = a.conn.prepareStatement(sql);
			sm.setString(1, simple.tihao);
			sm.setString(2, simple.timu);
			sm.setString(3, simple.answer);
			sm.execute();
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	private void jFileChooser4ActionPerformed(java.awt.event.ActionEvent evt) {//填空题
		// TODO add your handling code here:
		JFileChooser fd = new JFileChooser();
		//fd.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
		fd.showOpenDialog(null);
		File f = fd.getSelectedFile();
		if (f != null) {
			List<Simple2> simples = getText2(f);
			for (Simple2 simple : simples) {
				try {
					insert2(simple);
					JOptionPane.showMessageDialog(this, "出卷成功");
				} catch (ClassNotFoundException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}

			}

		}
	}

	public void insert2(Simple simple) throws ClassNotFoundException,
			SQLException {//多选题
		Shujukulianjie a = new Shujukulianjie();
		String b = jTextField1.getText();
		String sql = "INSERT INTO " + b
				+ "duoxuanti(tihao,timu,A,B,C,D,answer) VALUES(?,?,?,?,?,?,?)";
		PreparedStatement sm = null;
		try {
			sm = a.conn.prepareStatement(sql);
			sm.setString(1, simple.tihao);
			sm.setString(2, simple.timu);
			sm.setString(3, simple.A);
			sm.setString(4, simple.B);
			sm.setString(5, simple.C);
			sm.setString(6, simple.D);
			sm.setString(7, simple.answer);
			sm.execute();
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	private void jFileChooser2ActionPerformed(java.awt.event.ActionEvent evt) {//多选题
		// TODO add your handling code here:
		JFileChooser fd = new JFileChooser();
		//fd.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
		fd.showOpenDialog(null);
		File f = fd.getSelectedFile();
		if (f != null) {
			List<Simple> simples = getText(f);
			for (Simple simple : simples) {
				try {
					insert2(simple);
					JOptionPane.showMessageDialog(this, "出卷成功");
				} catch (ClassNotFoundException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}

			}

		}
	}

	public List<Simple1> getText1(File f) {//判断题
		List<Simple1> simples = new ArrayList<Simple1>();
		try {
			FileReader reader = new FileReader(f);
			BufferedReader bfReader = new BufferedReader(reader);
			String text = null;
			while ((text = bfReader.readLine()) != null) {
				String[] texts = text.split(" ");
				Simple1 simple = new Simple1();
				simple.tihao = texts[0];
				simple.timu = texts[1];
				simple.answer = texts[2];
				simples.add(simple);
			}
		} catch (Exception e) {
			e.printStackTrace();
			JOptionPane.showMessageDialog(this, "txt内容有问题");
		}
		return simples;
	}

	public void insert1(Simple1 simple) throws ClassNotFoundException,
			SQLException {//判断题
		Shujukulianjie a = new Shujukulianjie();
		String b = jTextField1.getText();
		String sql = "INSERT INTO " + b
				+ "panduan(tihao,timu,A,B,C,D,answer) VALUES(?,?,?,?,?,?,?)";
		PreparedStatement sm = null;
		try {
			sm = a.conn.prepareStatement(sql);
			sm.setString(1, simple.tihao);
			sm.setString(2, simple.timu);
			sm.setString(3, simple.answer);
			sm.execute();
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	private void jFileChooser3ActionPerformed(java.awt.event.ActionEvent evt) {//判断题
		// TODO add your handling code here:
		JFileChooser fd = new JFileChooser();
		//fd.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
		fd.showOpenDialog(null);
		File f = fd.getSelectedFile();
		if (f != null) {
			List<Simple1> simples = getText1(f);
			for (Simple1 simple : simples) {
				try {
					insert1(simple);
					JOptionPane.showMessageDialog(this, "出卷成功");
				} catch (ClassNotFoundException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}

			}

		}
	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//创建试卷
		// TODO add your handling code here:
		try {
			Shujukulianjie s = new Shujukulianjie();
			String a = jLabel6.getText();
			String b = jLabel7.getText();
			String sql = "CREATE TABLE "
					+ a
					+ "depaper(papername varchar(30),papershuliang varchar(30))";
			Statement stmt;
			stmt = s.conn.createStatement();
			stmt.executeUpdate(sql);
			String sql1 = "insert into " + a + "depaper(papername) values('"
					+ b + "')";
			stmt.executeUpdate(sql1);
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
			Shujukulianjie s;
			try {
				s = new Shujukulianjie();
				String a = jLabel6.getText();
				String b = jTextField1.getText();
				Statement stmt;
				stmt = s.conn.createStatement();
				String sql1 = "insert into " + a
						+ "depaper(papername) values('" + b + "')";
				String sql2 = "CREATE TABLE  "
						+ b
						+ "danxuan(tihao varchar(100),timu varchar(100),A varchar(100),"
						+ "B varchar(100),C varchar(100),D varchar(100),answer varchar(100))default character set utf8";
				String sql3 = "CREATE TABLE  "
						+ b
						+ "panduan(tihao varchar(100),timu varchar(100),answer varchar(100))default character set utf8";
				String sql4 = "CREATE TABLE  "
						+ b
						+ "duoxuan(tihao varchar(100),timu varchar(100),A varchar(100),"
						+ "B varchar(100),C varchar(100),D varchar(100),answer varchar(100))default character set utf8";
				String sql5 = "CREATE TABLE  "
						+ b
						+ "tiankong(tihao varchar(100),timu varchar(100),answer varchar(100))default character set utf8";
				String sql6 = "CREATE TABLE  "
						+ b
						+ "score(name varchar(100),score varchar(100))default character set utf8";
				stmt.executeUpdate(sql1);
				stmt.executeUpdate(sql2);
				stmt.executeUpdate(sql3);
				stmt.executeUpdate(sql4);
				stmt.executeUpdate(sql5);
				stmt.executeUpdate(sql6);
			} catch (ClassNotFoundException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
				JOptionPane.showMessageDialog(this, "试卷名已存在");
			} catch (SQLException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
				JOptionPane.showMessageDialog(this, "试卷名已存在");
			}

		}

	}

	public List<Simple> getText(File f) {//单选题
		List<Simple> simples = new ArrayList<Simple>();
		try {
			FileReader reader = new FileReader(f);
			BufferedReader bfReader = new BufferedReader(reader);
			String text = null;
			while ((text = bfReader.readLine()) != null) {
				String[] texts = text.split(" ");
				Simple simple = new Simple();
				simple.tihao = texts[0];
				simple.timu = texts[1];
				simple.A = texts[2];
				simple.B = texts[3];
				simple.C = texts[4];
				simple.D = texts[5];
				simple.answer = texts[6];
				simples.add(simple);
			}
		} catch (Exception e) {
			e.printStackTrace();
			JOptionPane.showMessageDialog(this, "txt内容有问题");
		}
		return simples;
	}

	public void insert(Simple simple) throws ClassNotFoundException,
			SQLException {//单选题
		Shujukulianjie a = new Shujukulianjie();
		String b = jTextField1.getText();
		String sql = "INSERT INTO " + b
				+ "danxuan(tihao,timu,A,B,C,D,answer) VALUES(?,?,?,?,?,?,?)";
		PreparedStatement sm = null;
		try {
			sm = a.conn.prepareStatement(sql);
			sm.setString(1, simple.tihao);
			sm.setString(2, simple.timu);
			sm.setString(3, simple.A);
			sm.setString(4, simple.B);
			sm.setString(5, simple.C);
			sm.setString(6, simple.D);
			sm.setString(7, simple.answer);
			sm.execute();
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	private void jFileChooser1ActionPerformed(java.awt.event.ActionEvent evt) {//单选
		// TODO add your handling code here:
		JFileChooser fd = new JFileChooser();
		//fd.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
		fd.showOpenDialog(null);
		File f = fd.getSelectedFile();
		if (f != null) {
			List<Simple> simples = getText(f);
			for (Simple simple : simples) {
				try {
					insert(simple);
					JOptionPane.showMessageDialog(this, "出卷成功");
				} catch (ClassNotFoundException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}

			}

		}

	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {

		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {

			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JFileChooser jFileChooser1;
	private javax.swing.JFileChooser jFileChooser2;
	private javax.swing.JFileChooser jFileChooser3;
	private javax.swing.JFileChooser jFileChooser4;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JTextField jTextField1;
	// End of variables declaration//GEN-END:variables

}

class Simple {
	String tihao;
	String timu;
	String A;
	String B;
	String C;
	String D;
	String answer;
}

class Simple1 {
	String tihao;
	String timu;
	String answer;
}

class Simple2 {
	String tihao;
	String timu;
	String answer;
}